#!/bin/sh

set -e

TARGET_DIR=$1

. $(dirname $0)/set-versions

NODEJS_DIR=node-v${NODEJS_VERSION}

tar xzf node-v${NODEJS_VERSION}.tar.gz

cd ${NODEJS_DIR}
make binary

mkdir -p ${TARGET_DIR}
tar xzf node-v*.tar.gz --directory ${TARGET_DIR} --strip-components 1
